// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:13be765e-5df2-41e7-9d08-74af6285980e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_JQ6wC4CY3",
    "aws_user_pools_web_client_id": "6endda605j4pf10tnva3tg6vr2",
    "oauth": {}
};


export default awsmobile;
